os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
          brew tap vapor/tap;
          brew update;
          brew install vapor ctls;
      else
          eval "$(curl -sL https://apt.vapor.sh)";
          sudo apt-get install vapor ctls;
          sudo chmod -R a+rx /usr/;
      fi
script:
  - swift build
  - swift build -c release
